version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - mysql
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  application:
    build: .
    volumes:
      - ./src:/usr/netguru/src
    command: npm run dev:${VERSION}
    depends_on:
      - prisma
    ports:
      - "4000:4000"
volumes:
  mysql: ~
