version: '3.4'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 3000:3000

volumes:
  mysql: ~
