version: '3.4'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    environment:
      DATABASE_URL: $DATABASE_URL
    volumes:
      - .:/app
      - /app/node_modules/
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
