version: '3.4'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    volumes:
      - mysql:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 3000:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql: ~
